# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish dead-bug.csproj -c Release -o website -a x64
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: website/**
        if-no-files-found: error
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: website
        path: distfiles
    - name: deploy
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: distfiles/*
        target: /var/www/dead-bug
    - name: Restart Service
      uses: appleboy/ssh-action@v0.1.2
      with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{ secrets.PASSPHRASE }}
              
          script: |
                sudo systemctl restart kestrel-dead-bug.service
                echo 'Deployment success'
