on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{ secrets.PASSPHRASE }}

          script: |
            cd dev-repos
            rm -rf dead-bug
            git clone https://github.com/jsimpson15011/dead-bug.git
            cd dead-bug
            echo 'Deployment success'
      
